### ISSUE TITLE
PWM will ignore PV-Load

### ISSUE THREAD

**Issue by CGES19** [johannesegger/Ohmcontrol#2]
The solution of PWM with full wave control does not bring the desired result. The power is controlled via this PWM, but it does nothing to optimize the self-consumption of the PV power. Each full wave loads the circuit with 100%. I.e. I load with 3000 watts, but the PV system supplies only 2000 watts, then the missing 1000 watts are supplied by the power supplier, which you also have to pay. An optimization only works if every single sine wave of the alternating current is chopped into small parts (PWM).

**Comment by johannesegger** [comment]
Thanks for your input.

I guess that depends on your supplier. For me it looks like billing is based on 15 minutes intervals, so what I produce and what I consume is summed up for 15 minutes and the result is what I pay for or what I earn.

Here is my consumption data for May 2023 (I chose May here because I produced a lot and self-consumed a lot):

<img width="375" alt="solar-web" src="https://github.com/johannesegger/Ohmcontrol/assets/237707/03c344b3-e858-4325-9610-b164b9f3a8a5">

And here is what I paid for (265 kWh in total):

<img width="985" alt="energie-ag" src="https://github.com/johannesegger/Ohmcontrol/assets/237707/67209914-e049-49bb-80b6-110ab59d8a7a">

Are you sure that your supplier bills based on every sine wave? That would be *a lot* of data. Also someone told me that [switching during a wave](https://en.wikipedia.org/wiki/Phase-fired_controller) is not good because many devices doing so change the form of the sine wave until it's no longer recognizable as a sine wave.
